#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:

      #jpa ddl-auto
        #create: DROP 후 CREATE
        #create-drop: DROP 후 CREATE 후 DROP
        #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 삭제는 불가능)
        #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: create

    #jpa format
    properties:
      hibernate:
        format_sql: true

  #log
  output:
    ansi:
      enabled: always

